version: '3.9'

services:

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=dark
      - POSTGRES_PASSWORD=pyro
    ports:
      - 5432:5432
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.125'
          memory: 64M
        reservations:
          memory: 32M

  darkpyro:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    restart: always
    environment:
      - DATABASE_URL=postgresql://dark:pyro@db:5432/db
      - GIT_PYTHON_REFRESH=quiet
    env_file:
      - config.env
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          memory: 128M
